# The title of the site
title = "tforgione.fr"

# The URL the site will be built for
# base_url = "http://localhost:8000/"
base_url = "https://storage.tforgione.fr/zola/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[extra]
# Put all your custom variables here

# Author of the page
author = "Thomas Forgione"

# Role of the author
role = "PhD Student"

# Whether the navbar should be screen wide or page wide
wide_navbar = false

# Organizations of the author
organizations = [ { name = "IRIT, Toulouse" } ]

# Url of your profile pic
# You should put your portrait in the static directory.
portrait = "/static/img/portrait.jpg"

# The links you want to put on the left of the navbar
menu_left = [
]

# The links you want to put on the right of the navbar:w
menu_right = [
    { name = "Publications", link = "/publications" },
    { name = "Demos", link = "/demo" },
    { name = "Contact", link = "/#contact" }
]

# Social icons that will appear under your profile box
social_icons = [
{icon="fa-envelope", icon_pack="fa", link="mailto:thomas@forgione.fr"},
{icon="ai-google-scholar", icon_pack="ai", link="https://scholar.google.fr/citations?user=m0Ia3KEAAAAJ"},
{icon="fa-git", icon_pack="fab", link="https://gitea.tforgione.fr/tforgione/"}
]

# Your interests
interests = [
    { label = "Rust", link = "https://www.rust-lang.org" },
    { label = "Ubports Ubuntu Touch", link = "https://ubports.com/)" },
    { label = "3D graphics" },
    { label = "Multimedia" },
    { label = "Guitar" }
]

# Your diplomas
education = [
{course = "Engineer in IT and applied mathematics", institution = "ENSEEIHT, Toulouse, France", year = 2015},
]

# The ways people can contact you
contact_links = [
  # {icon = "twitter", icon_pack = "fab", name = "DM Me", link = "https://twitter.com/Twitter"},
  # {icon = "skype", icon_pack = "fab", name = "Skype Me", link = "skype:echo123?call"},
  # {icon = "keybase", icon_pack = "fab", name = "Chat on Keybase", link = "https://keybase.io/"},
  # {icon = "comments", icon_pack = "fas", name = "Discuss on Forum", link = "https://discourse.gohugo.io"},
  {icon = "fa-telegram", icon_pack = "fab", name = "@tforgione", link = "https://telegram.me/@tforgione"},
  {icon="fa-envelope", icon_pack="fa", name = "thomas@forgione.fr", link="mailto:thomas@forgione.fr"},
]

# Choose your style among these
# style = "primary"
style = "link"
# style = "info"
# style = "success"
# style = "warning"
# style = "danger"
# style = "black"
# style = "dark"
# style = "light"
# style = "white"
